### ISSUE TITLE
createAction default handler

### ISSUE THREAD

**Issue by Bobris** [karelsteinmetz/fun-model#11]
https://github.com/karelsteinmetz/fun-model/blob/master/src/actionFactory.ts#L31

First it has wrong type and even wrong default implementation. But main question does it even make sense to allow action with just default handler?

**Comment by svatal** [comment]
Default handler makes sense and is correct, but only if TState === TParams (as a replace of the whole substate). In other cases, the default handler and it's accessibility can make a lot of mess.

IMHO the solution should be either remove it (simple solution, as the added value is really small) or make two entry points to the function - one for TState === TParams with default handler and the other one without default handler ...

**Comment by karelsteinmetz** [comment]
so...let's create new action factory that could be like this:
createReplaceAction<TState extends s.IState | null>(cursor: f.Icursor<TState>)
and default handler could be removed from createAction but there will be occurred one braking change in createAction.
I'm gonna check this opinion with contributor of this feature

**Comment by keeema** [comment]
It looks ok for me.
